version: 2.1

default_steps: &default_steps
  steps:
    - checkout
    # Install PhantomJS
    - run: >-
          sudo apt-get update && sudo apt-get install -y fontconfig
          && wget -O /tmp/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
          && tar -xjf /tmp/phantomjs.tar.bz2 -C /tmp
          && sudo mv /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
    - run: gem update --system
    - run: bundle install
    - run: bundle exec rake test

jobs:
  ruby_latest_with_percy:
    # This is the one environment where we'll capture and upload snapshots in CI.
    docker:
      - image: circleci/ruby:latest-node-browsers
    <<: *default_steps
  ruby_25:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    environment:
      PERCY_ENABLE: 0
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - ruby_latest_with_percy
      - ruby_25
